#!/usr/bin/env bash

# Update all Ruby Gems

# Run as root
if [ $EUID -ne 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

# Update Ruby Gems using the Ruby Gem `rubygems-update`
if [ -f "$HOME/.gem/ruby/2.4.0/bin/update_rubygems" ]; then
  set -v
  gem update --system
  set +v
else
  set -v
  echo "This script requires the `rubygems-update` gem to be installed."
  set +v
fi

# EOF
