#!/usr/bin/env bash

# Update all Ruby Gems

# Update the Ruby Gems packet manager using the Ruby Gem `rubygems-update`
if [ -f "$HOME/.gem/ruby/2.4.0/bin/update_rubygems" ]; then
  set -v
  sudo gem update --system
  set +v
else
  set -v
  echo "This script requires the `rubygems-update` gem to be installed."
  set +v
fi

# Update all installed gems
set -v
gem update

# EOF
