#!/usr/bin/env bash

# If no URL given. Opens browser. For using script as $BROWSER.
# [ -z "$1" ] && {
#   "$BROWSER"
#   exit
# }

# Calling global OS variable set in `.shellcommon`
case $OS in
  "Linux" )

    case "$1" in
      *mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
        setsid -f mpv -quiet "$1" >/dev/null 2>&1 ;;
      *png|*jpg|*jpe|*jpeg|*gif)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && eog "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
      *.cdninstagram.com/v/*_n.mp4?_nc*)
        var="$(echo "$1" | sed "s/&amp;/\&/g" | sed "s/_nc/\&_nc/2")" && setsid -f mpv -quiet "$var" >/dev/null 2>&1 ;;
      *.cdninstagram.com/v/*_n.jpg?_nc*|*media?size*)
        var="$(echo "$1" | sed "s/.*\///" | sed "s/.jpg.*/.jpg/")" && curl -sL "$1" > "/tmp/$var" && eog "/tmp/$var" >/dev/null 2>&1 & ;;
      *mp3|*flac|*opus|*mp3?source*)
        setsid -f tsp curl -LO "$1" >/dev/null 2>&1 ;;
      *pdf?source*)
        setsid -f evince curl -LO "$1" >/dev/null 2>&1 ;;
      *)
        if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
        else setsid -f "$BROWSER" "$1" >/dev/null 2>&1; fi ;;
     esac
esac

case $OS in
  "Darwin" )

    case "$1" in
      *.mkv|*.webm|*.mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
        open -a iina "$1" >/dev/null 2>&1 ;;

      *.png|*.jpg|*.jpe|*.jpeg|*.gif|*.vgif)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && open -a preview "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;

      *.aiff|*.flac|*.opus|*.m4a|*.mp3|*.wav)
        open -a vlc curl -LO "$1" >/dev/null 2>&1 ;;

      *.ai|*.pdf|*.ps)
        open -a preview curl -LO "$1" >/dev/null 2>&1 ;;

      *.md)
        open -a "ia writer" curl -LO "$1" >/dev/null 2>&1 ;;

      *.bash|*.cnf|*.conf|*.cpp|*.css|*.c|*.html|*.h|*.ini|*.js|*.php|*.py|*rc|*.sh|*.txt)
        "$EDITOR" curl -LO "$1" >/dev/null 2>&1 ;;

      *)
        if [ -f "$1" ]; then "$EDITOR" "$1"
        # else w3m curl -LO "$1" >/dev/null 2>&1; fi ;;
        else w3m "$1"; fi ;;
     esac
esac

# EOF
