#!/usr/bin/env bash

# If no URL given. Opens browser. For using script as $BROWSER.
# [ -z "$1" ] && {
#   "$BROWSER"
#   exit
# }

# Calling global OS variable set in `.shellcommon`
case $OS in
  "Linux" )

    case "$1" in
      *.avi|*.mkv|*.mov|*.webm|*.gifv|*.mp4|*.m4v|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
        setsid -f mpv -quiet "$1" >/dev/null 2>&1 ;;

      *.png|*.jpg|*.jpe|*.jpeg|*.gif|*.vgif)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && eog --fullscreen "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;

      *.aiff|*.flac|*.opus|*.m4a|*.mp3|*.wav)
        setsid -f rhythmbox "$1" >/dev/null 2>&1 ;;

      *.ai|*.pdf|*.ps)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && setsid -f mupdf "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;

      *.md)
        "$EDITOR" "$1" 2>&1 ;;

      *.bash|*.cnf|*.conf|*.cpp|*.css|*.c|*.h|*.ini|*.js|*.php|*.py|*rc|*.sh|*.txt)
        "$EDITOR" "$1" 2>&1 ;;

      *)
        if [ -f "$1" ]; then "$EDITOR" "$1";
        else url-filter-main "$1" 2>/dev/null;
        fi ;;
     esac
esac

case $OS in
  "Darwin" )

    case "$1" in
      *.avi|*.mkvi|*.mov|*.webm|*.gifv|*.mp4|*.m4v|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
        open -a iina "$1" >/dev/null 2>&1 ;;

      *.png|*.jpg|*.jpe|*.jpeg|*.gif|*.vgif)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && open -a preview "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;

      *.aiff|*.flac|*.opus|*.m4a|*.mp3|*.wav)
curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && open -a vlc "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;

      *.ai|*.pdf|*.ps)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && open -a preview "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;

      *.md)
        open -a "ia writer" "$1" 2>&1 ;;

      *.bash|*.cnf|*.conf|*.cpp|*.css|*.c|*.h|*.ini|*.js|*.php|*.py|*rc|*.sh|*.txt)
        "$EDITOR" "$1" 2>&1 ;;

      *)
        if [ -f "$1" ]; then "$EDITOR" "$1";
        else url-filter-main "$1" 2>/dev/null;
        fi ;;
     esac
esac

# EOF
