#!/usr/bin/env bash

# Run as root
# if [ $EUID -ne 0 ]; then
#     sudo "$0" "$@"
#     exit $?
# fi

# Echo commands
set -v

# Update PIP itself
pip install --user --upgrade pip
pip3 install --user --upgrade pip

# Update all Python 2.X PIP
# pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install --user

# Update all Python 3.X PIP
pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install ---user

# EOF
