#!/usr/bin/env bash

# Run as root
if [ $EUID -ne 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

# Update and sync `chronyd` with the machine time, but fast.
printf '#### Get the time from NTP servers ####\n'
chronyc -a 'burst 4/4'

# Make `chronyd` step the clock instead of slewing.
printf '\n#### Wait 10s before makestep      ####\n'
sleep 10
chronyc -a makestep

# See chrony and date agree
printf '\n#### Chrony                        ####\n'
chronyc tracking
printf '\n#### Date                          ####\n'
date -u

# EOF
