#!/usr/bin/env sh

# Script to filter main text of a webpage and pipe it in to `w3m`
# REQUIRES: `trafilatura` a Python script
# Accepts first argument as

trafilatura -u "$1" --parallel 4 --no-comments --formatting | sed ':a;N;$!ba;s/\n/\n\n/g' | fold -w 65 -s | w3m

# Output to XML, but I haven't found an easy way to get to a PDF.
# trafilatura --xml --formatting --links --parallel 4 --verbose -u "$1" -o ~/Documents/

# EOF
