#!/usr/bin/env bash

# Redirect Twitter links through the Twitter-via-Nitter proxy
if [[ "$1" =~ twitter\.com ]]; then
  nitter_url=$(echo "$1" | sed "s#twitter.com#nitter.net#g")
  w3m "$nitter_url"
else

# Script to filter webpage bodycopy and pipe it in a pager.
# REQUIRES: `trafilatura` a Python script (install with `virtualenv`).
  # Accepts first argument as URL
  trafilatura -u "$1" --parallel 4 --no-comments --formatting | \
  # Cross-platform GNU Sed and BSD Sed.
  sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\n\n/g' | \
  # github.com/charmbracelet/glow
  glow -
fi

# EOF
