theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
